# Generated by Django 3.2.3 on 2022-01-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.CharField(max_length=20)),
                ('iname', models.CharField(max_length=100)),
                ('iquantity', models.IntegerField(max_length=100)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
